# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e305470cdcdb371c05ec247a2ca50c82415e44092ce27078e7e2016899f30044aa1ab434efd7402451847ae2d6d98a412faca5813a3dddd66a075c77b80b6c2

test:
  secret_key_base: e4d165f69a097901a36e5e9675ea0e6a73c0c6b76272e8f22d16d2241a945abed88fc4363b6525c24442e0b9c9ab9ae6f25ee40ff0657ea6042edaed33097e8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
